syntax = "proto3";

package auth.v1;

import "google/protobuf/empty.proto";

service AuthService {
    rpc SendOtp(SendOtpRequestDto) returns (SendOtpResponseDto);
    rpc VerifyOtp(VerifyOtpRequestDto) returns (VerifyOtpResponseDto);
    rpc Refresh(RefreshRequestDto) returns (RefreshResponseDto);

    rpc TelegramInit(google.protobuf.Empty) returns (TelegramInitResponseDto);
    rpc TelegramVerify(TelegramVerifyRequestDto) returns (TelegramVerifyResponseDto);

}

message SendOtpRequestDto {
    string identifier = 1;
    string type = 2;
}

message SendOtpResponseDto {
    string message = 1;
}

message VerifyOtpRequestDto {
    string identifier = 1;
    string type = 2;
    string code = 3;
}

message VerifyOtpResponseDto {
    string access_token = 1;
    string refresh_token = 2;
}

message RefreshRequestDto {
    string refresh_token = 1;
}

message RefreshResponseDto {
    string access_token = 1;
    string refresh_token = 2;
}

message TelegramInitResponseDto {
    string url = 1;
}

message TelegramVerifyRequestDto {
    map<string, string> query = 1;
}

message TelegramVerifyResponseDto {
    oneof result {
        string url = 1;
        string access_token = 2;
        string refresh_token = 3;
    }
}